server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource: #docker run -d --restart always --name polar-postgres -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=polardb_catalog -p 5432:5432 postgres:14.4
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
    import: "optional:configserver:"
  cloud:
    #config:
    #  uri: http://localhost:8888
    #  request-connect-timeout: 5000
    #  request-read-timeout: 5000
    #  fail-fast: true
    #  retry:
    #    max-attempts: 6
    #    initial-interval: 1000
    #    max-interval: 2000
    #    multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!